### ISSUE TITLE
Build Errors - see attached

### ISSUE THREAD

**Issue by mayurjobanputra** [roozbehzarei/SuperWebView#2]
Getting a lot of "Duplicate class" errors. See attached.

[superwebview-errors.txt](https://github.com/roozbehzarei/SuperWebView/files/11715679/superwebview-errors.txt)

**Comment by roozbehzarei** [comment]
> 

It seems like there's an issue with one of your dependencies. Can you provide your build.gradle files?

**Comment by roozbehzarei** [comment]
It seems like the issue is caused by updating the AGP but not Gradle itself. You should double check for compatibility issues before upgrading the project's structure. I just updated SuperWebView to the latest dependencies/plugins. You should be able to build without issues now.
