### ISSUE TITLE
Unresolved reference:

### ISSUE THREAD

**Issue by alvlp-code** [roozbehzarei/SuperWebView#3]

**Comment by alvlp-code** [comment]
Unresolved reference: keyboardinnerColor
Unresolved reference: sppip
![Screenshot from 2023-09-09 08 22 23](https://github.com/roozbehzarei/SuperWebView/assets/129393234/d1dac4d9-fb2b-4bda-b3c4-436c75dd261a)

**Comment by roozbehzarei** [comment]
> Unresolved reference: keyboardinnerColor Unresolved reference: sppip ![Screenshot from 2023-09-09 08 22 23](https://user-images.githubusercontent.com/129393234/266754007-d1dac4d9-fb2b-4bda-b3c4-436c75dd261a.png)

I reckon you have changed the value of `spinnerColor` and `spinnerTypedValue` variables. Can you share that part of your code?
