### ISSUE TITLE
Local

### ISSUE THREAD

**Issue by nodefive** [roozbehzarei/SuperWebView#4]
Is it possible to load a local build-in file instead?

**Comment by roozbehzarei** [comment]
Hello @nodefive,

Of course. Follow these steps to load a file locally:
1. Go to the app > right-click > New > Folder > Asset Folder and create the asset folder.
2. Place a sample `my_html_file.html` inside the folder.
3. Change the `WEBSITE` constant value to `file:///android_asset/my_html_file.html`.
