### ISSUE TITLE
Load web pages in-app instead of external browser

### ISSUE THREAD

**Issue by kao0312** [roozbehzarei/SuperWebView#8]
Currently, when users click on external links within our WebView app, they are redirected to the device's default web browser. We'd like to modify this behavior so that all links open within the app itself, using our WebView. This would allow users to navigate to new web pages without leaving the app environment, providing a more seamless browsing experience and keeping users engaged with our app.

**Comment by roozbehzarei** [comment]
> Currently, when users click on external links within our WebView app, they are redirected to the device's default web browser. We'd like to modify this behavior so that all links open within the app itself, using our WebView. This would allow users to navigate to new web pages without leaving the app environment, providing a more seamless browsing experience and keeping users engaged with our app.

Thank you for using SuperWebView. To achieve your goal, refer to `MainActivity.kt` file and remove the `shouldOverrideUrlLoading` method (line 120 to 131).

**Comment by kao0312** [comment]
Thank you very much. I've already solved this problem.
