### ISSUE TITLE
Unable to open embedded youtube video in full screen view

### ISSUE THREAD

**Issue by aplusclients** [roozbehzarei/SuperWebView#9]
Unable to open embedded youtube video in full screen view.  Embedded YT video will play in the browser but pressing the full screen button [  ] does nothing.  Thank you.

**Comment by roozbehzarei** [comment]
Thank you for reporting this issue @aplusclients. I'm investigating and will post a fix as soon as possible.

**Comment by roozbehzarei** [comment]
Commit c80e66a fixed this issue.
